import logging
import os
import json
from datetime import datetime
from pathlib import Path

from jarvisx.workflows.nodes.base import BaseNodeExecutor
from jarvisx.config.configs import WORKSPACE_BASE_PATH

logger = logging.getLogger(__name__)


class FileSaveNodeExecutor(BaseNodeExecutor):
    async def execute(
        self,
        config: dict,
        input_data: dict,
        node_data: dict
    ) -> dict:
        filename_template = config.get("filename", "output_{{timestamp}}")
        file_format = config.get("format", "txt")
        content_template = config.get("content", "{{input.response}}")
        subdirectory = config.get("subdirectory", "workflow_outputs")
        
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        context = {
            "input": input_data,
            "timestamp": timestamp,
            "date": datetime.utcnow().strftime("%Y-%m-%d"),
        }
        
        filename = self.interpolate_variables(filename_template, context)
        content = self.interpolate_variables(content_template, context)
        
        if not filename.endswith(f".{file_format}"):
            filename = f"{filename}.{file_format}"
        
        filename = self._sanitize_filename(filename)
        
        output_dir = Path(WORKSPACE_BASE_PATH) / subdirectory
        output_dir.mkdir(parents=True, exist_ok=True)
        
        file_path = output_dir / filename
        
        try:
            if file_format == "json":
                file_content = self._format_json(input_data, content)
            elif file_format == "md":
                file_content = self._format_markdown(content, input_data)
            elif file_format == "pdf":
                return await self._save_pdf(file_path, content, input_data)
            else:
                file_content = content
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(file_content)
            
            logger.info(f"[FileSaveNode] File saved to {file_path}")
            
            return {
                "success": True,
                "message": f"File saved successfully",
                "file_path": str(file_path),
                "filename": filename,
                "format": file_format,
                "size_bytes": os.path.getsize(file_path)
            }
            
        except Exception as e:
            logger.error(f"[FileSaveNode] Failed to save file: {e}")
            return {
                "success": False,
                "error": str(e),
                "filename": filename
            }
    
    def _sanitize_filename(self, filename: str) -> str:
        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            filename = filename.replace(char, "_")
        return filename
    
    def _format_json(self, input_data: dict, content: str) -> str:
        try:
            data = json.loads(content)
        except json.JSONDecodeError:
            data = {
                "content": content,
                "raw_data": input_data
            }
        return json.dumps(data, indent=2, ensure_ascii=False)
    
    def _format_markdown(self, content: str, input_data: dict) -> str:
        if content.startswith("#"):
            return content
        
        md_content = f"# Workflow Output\n\n"
        md_content += f"**Generated:** {datetime.utcnow().isoformat()}Z\n\n"
        md_content += "---\n\n"
        md_content += content
        
        if "agent" in input_data:
            md_content += f"\n\n---\n\n*Generated by {input_data['agent']} agent*"
        
        return md_content
    
    async def _save_pdf(self, file_path: Path, content: str, input_data: dict) -> dict:
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.units import inch
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        except ImportError:
            logger.error("[FileSaveNode] reportlab not installed - cannot generate PDF")
            return {
                "success": False,
                "error": "PDF generation requires the 'reportlab' package. Install it with: pip install reportlab",
                "filename": file_path.name,
                "format": "pdf",
                "hint": "Install reportlab or choose a different format (txt, json, md)"
            }
        
        try:
            doc = SimpleDocTemplate(str(file_path), pagesize=letter)
            styles = getSampleStyleSheet()
            story = []
            
            story.append(Paragraph("Workflow Output", styles['Heading1']))
            story.append(Spacer(1, 0.25 * inch))
            story.append(Paragraph(f"Generated: {datetime.utcnow().isoformat()}Z", styles['Normal']))
            story.append(Spacer(1, 0.5 * inch))
            
            paragraphs = content.split("\n\n")
            for para in paragraphs:
                if para.strip():
                    safe_para = para.replace("\n", "<br/>").replace("&", "&amp;").replace("<br/>", "<br/>")
                    try:
                        story.append(Paragraph(safe_para, styles['Normal']))
                    except Exception:
                        story.append(Paragraph(para.replace("\n", " ")[:500], styles['Normal']))
                    story.append(Spacer(1, 0.2 * inch))
            
            doc.build(story)
            
            return {
                "success": True,
                "message": "PDF file saved successfully",
                "file_path": str(file_path),
                "filename": file_path.name,
                "format": "pdf",
                "size_bytes": os.path.getsize(file_path)
            }
            
        except Exception as e:
            logger.error(f"[FileSaveNode] Failed to generate PDF: {e}")
            return {
                "success": False,
                "error": str(e),
                "filename": file_path.name,
                "format": "pdf"
            }
